name: Deploy GitHub Pages

on:
  release:
    types: [ released ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:

  deploy:
    name: Deploy
    defaults:
      run:
        working-directory: example/react
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./
      - run: npm run build
        working-directory: ./
      - run: npm ci --omit=dev --audit=false --fund=false
      - run: npm run build
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: example/react/build
      - id: deployment
        uses: actions/deploy-pages@v2
